//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpanAidAdmin.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TruckLogics_Ticket
    {
        public long TL_Ticket_Id { get; set; }
        public string TL_Ticket_Number { get; set; }
        public string TL_User_Name { get; set; }
        public string Tl_Email_Address { get; set; }
        public string TL_Module_Name { get; set; }
        public string TL_Ticket_Description { get; set; }
        public string TL_Ticket_Status { get; set; }
        public bool TL_Is_PushNotification { get; set; }
        public bool Tl_Is_Email_Send { get; set; }
        public bool TL_Is_Text_Send { get; set; }
        public string TL_Priority { get; set; }
        public byte[] TL_Attachment { get; set; }
        public string TL_Phone_Number { get; set; }
        public string TL_Ticket_Type { get; set; }
        public bool TL_Is_Deleted { get; set; }
        public System.DateTime TL_Ticket_Create_Date { get; set; }
        public System.DateTime TL_Ticket_Update_Date { get; set; }
    }
}
